export const banks = [
  {
    name: "Ngân hàng TMCP Công thương Việt Nam",
    code: "ICB",
    shortName: "VietinBank",
    logo: "https://api.vietqr.io/img/ICB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Ngoại Thương Việt Nam",
    code: "VCB",
    shortName: "Vietcombank",
    logo: "https://api.vietqr.io/img/VCB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam",
    code: "BIDV",
    shortName: "BIDV",
    logo: "https://api.vietqr.io/img/BIDV.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam",
    code: "VBA",
    shortName: "Agribank",
    logo: "https://api.vietqr.io/img/VBA.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Phương Đông",
    code: "OCB",
    shortName: "OCB",
    logo: "https://api.vietqr.io/img/OCB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Quân đội",
    code: "MB",
    shortName: "MBBank",
    logo: "https://api.vietqr.io/img/MB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Kỹ thương Việt Nam",
    code: "TCB",
    shortName: "Techcombank",
    logo: "https://api.vietqr.io/img/TCB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Á Châu",
    code: "ACB",
    shortName: "ACB",
    logo: "https://api.vietqr.io/img/ACB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Việt Nam Thịnh Vượng",
    code: "VPB",
    shortName: "VPBank",
    logo: "https://api.vietqr.io/img/VPB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Tiên Phong",
    code: "TPB",
    shortName: "TPBank",
    logo: "https://api.vietqr.io/img/TPB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Sài Gòn Thương Tín",
    code: "STB",
    shortName: "Sacombank",
    logo: "https://api.vietqr.io/img/STB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh",
    code: "HDB",
    shortName: "HDBank",
    logo: "https://api.vietqr.io/img/HDB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Bản Việt",
    code: "VCCB",
    shortName: "VietCapitalBank",
    logo: "https://api.vietqr.io/img/VCCB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Sài Gòn",
    code: "SCB",
    shortName: "SCB",
    logo: "https://api.vietqr.io/img/SCB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Quốc tế Việt Nam",
    code: "VIB",
    shortName: "VIB",
    logo: "https://api.vietqr.io/img/VIB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Sài Gòn - Hà Nội",
    code: "SHB",
    shortName: "SHB",
    logo: "https://api.vietqr.io/img/SHB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Xuất Nhập khẩu Việt Nam",
    code: "EIB",
    shortName: "Eximbank",
    logo: "https://api.vietqr.io/img/EIB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Hàng Hải",
    code: "MSB",
    shortName: "MSB",
    logo: "https://api.vietqr.io/img/MSB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "TMCP Việt Nam Thịnh Vượng - Ngân hàng số CAKE by VPBank",
    code: "CAKE",
    shortName: "CAKE",
    logo: "https://api.vietqr.io/img/CAKE.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "TMCP Việt Nam Thịnh Vượng - Ngân hàng số Ubank by VPBank",
    code: "Ubank",
    shortName: "Ubank",
    logo: "https://api.vietqr.io/img/UBANK.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Viettel Money",
    code: "VTLMONEY",
    shortName: "ViettelMoney",
    logo: "https://api.vietqr.io/img/VIETTELMONEY.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "VNPT Money",
    code: "VNPTMONEY",
    shortName: "VNPTMoney",
    logo: "https://api.vietqr.io/img/VNPTMONEY.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Sài Gòn Công Thương",
    code: "SGICB",
    shortName: "SaigonBank",
    logo: "https://api.vietqr.io/img/SGICB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Bắc Á",
    code: "BAB",
    shortName: "BacABank",
    logo: "https://api.vietqr.io/img/BAB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Đại Chúng Việt Nam",
    code: "PVCB",
    shortName: "PVcomBank",
    logo: "https://api.vietqr.io/img/PVCB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng Thương mại TNHH MTV Đại Dương",
    code: "Oceanbank",
    shortName: "Oceanbank",
    logo: "https://api.vietqr.io/img/OCEANBANK.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Quốc Dân",
    code: "NCB",
    shortName: "NCB",
    logo: "https://api.vietqr.io/img/NCB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TNHH MTV Shinhan Việt Nam",
    code: "SHBVN",
    shortName: "ShinhanBank",
    logo: "https://api.vietqr.io/img/SHBVN.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP An Bình",
    code: "ABB",
    shortName: "ABBANK",
    logo: "https://api.vietqr.io/img/ABB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Việt Á",
    code: "VAB",
    shortName: "VietABank",
    logo: "https://api.vietqr.io/img/VAB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Nam Á",
    code: "NAB",
    shortName: "NamABank",
    logo: "https://api.vietqr.io/img/NAB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Xăng dầu Petrolimex",
    code: "PGB",
    shortName: "PGBank",
    logo: "https://api.vietqr.io/img/PGB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Việt Nam Thương Tín",
    code: "VIETBANK",
    shortName: "VietBank",
    logo: "https://api.vietqr.io/img/VIETBANK.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Bảo Việt",
    code: "BVB",
    shortName: "BaoVietBank",
    logo: "https://api.vietqr.io/img/BVB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Đông Nam Á",
    code: "SEAB",
    shortName: "SeABank",
    logo: "https://api.vietqr.io/img/SEAB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng Hợp tác xã Việt Nam",
    code: "COOPBANK",
    shortName: "COOPBANK",
    logo: "https://api.vietqr.io/img/COOPBANK.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Bưu Điện Liên Việt",
    code: "LPB",
    shortName: "LienVietPostBank",
    logo: "https://api.vietqr.io/img/LPB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Kiên Long",
    code: "KLB",
    shortName: "KienLongBank",
    logo: "https://api.vietqr.io/img/KLB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng Đại chúng TNHH Kasikornbank",
    code: "KBank",
    shortName: "KBank",
    logo: "https://api.vietqr.io/img/KBANK.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng Liên doanh Việt - Nga",
    code: "VRB",
    shortName: "VRB",
    logo: "https://api.vietqr.io/img/VRB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TNHH MTV Standard Chartered Bank Việt Nam",
    code: "SCVN",
    shortName: "StandardChartered",
    logo: "https://api.vietqr.io/img/SCVN.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng Nonghyup - Chi nhánh Hà Nội",
    code: "NHB HN",
    shortName: "Nonghyup",
    logo: "https://api.vietqr.io/img/NHB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TNHH Indovina",
    code: "IVB",
    shortName: "IndovinaBank",
    logo: "https://api.vietqr.io/img/IVB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh TP. Hồ Chí Minh",
    code: "IBK - HCM",
    shortName: "IBKHCM",
    logo: "https://api.vietqr.io/img/IBK.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng Kookmin - Chi nhánh Thành phố Hồ Chí Minh",
    code: "KBHCM",
    shortName: "KookminHCM",
    logo: "https://api.vietqr.io/img/KBHCM.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng Kookmin - Chi nhánh Hà Nội",
    code: "KBHN",
    shortName: "KookminHN",
    logo: "https://api.vietqr.io/img/KBHN.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TNHH MTV Woori Việt Nam",
    code: "WVN",
    shortName: "Woori",
    logo: "https://api.vietqr.io/img/WVN.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TNHH MTV HSBC (Việt Nam)",
    code: "HSBC",
    shortName: "HSBC",
    logo: "https://api.vietqr.io/img/HSBC.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng Thương mại TNHH MTV Xây dựng Việt Nam",
    code: "CBB",
    shortName: "CBBank",
    logo: "https://api.vietqr.io/img/CBB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh Hà Nội",
    code: "IBK - HN",
    shortName: "IBKHN",
    logo: "https://api.vietqr.io/img/IBK.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TNHH MTV CIMB Việt Nam",
    code: "CIMB",
    shortName: "CIMB",
    logo: "https://api.vietqr.io/img/CIMB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "DBS Bank Ltd - Chi nhánh Thành phố Hồ Chí Minh",
    code: "DBS",
    shortName: "DBSBank",
    logo: "https://api.vietqr.io/img/DBS.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Đông Á",
    code: "DOB",
    shortName: "DongABank",
    logo: "https://api.vietqr.io/img/DOB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng Thương mại TNHH MTV Dầu Khí Toàn Cầu",
    code: "GPB",
    shortName: "GPBank",
    logo: "https://api.vietqr.io/img/GPB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TNHH MTV Public Việt Nam",
    code: "PBVN",
    shortName: "PublicBank",
    logo: "https://api.vietqr.io/img/PBVN.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng United Overseas - Chi nhánh TP. Hồ Chí Minh",
    code: "UOB",
    shortName: "UnitedOverseas",
    logo: "https://api.vietqr.io/img/UOB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TNHH MTV Hong Leong Việt Nam",
    code: "HLBVN",
    shortName: "HongLeong",
    logo: "https://api.vietqr.io/img/HLBVN.png",
    background: require("~/assets/images/bg/bg.jpg"),
  }
]
export const activeBanks = [
  {
    name: "Ngân hàng TMCP Kỹ thương Việt Nam",
    code: "TCB",
    shortName: "Techcombank",
    logo: "https://api.vietqr.io/img/TCB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam",
    code: "BIDV",
    shortName: "BIDV",
    logo: "https://api.vietqr.io/img/BIDV.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
  {
    name: "Ngân hàng TMCP Ngoại Thương Việt Nam",
    code: "VCB",
    shortName: "Vietcombank",
    logo: "https://api.vietqr.io/img/VCB.png",
    background: require("~/assets/images/bg/bg.jpg"),
  },
]